data_dir = '/home/kb541/nas/jz/L16/DeepLungData/'
config = {'train_data_path': [data_dir + '$DOWNLOADLUNA16PATH/subset0/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset1/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset2/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset3/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset4/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset5/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset6/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset7/',
                              data_dir + '$DOWNLOADLUNA16PATH/subset8/'],
          'val_data_path': [data_dir + '$DOWNLOADLUNA16PATH/subset9/'],
          'test_data_path': [data_dir + '$DOWNLOADLUNA16PATH/subset9/'],

          'train_preprocess_result_path': data_dir + '$LUNA16PROPOCESSPATH/',
          # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path': data_dir + '$LUNA16PROPOCESSPATH/',
          # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path': data_dir + '$LUNA16PROPOCESSPATH/',

          'train_annos_path': data_dir + '$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          'val_annos_path': data_dir + '$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          'test_annos_path': data_dir + '$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',

          'black_list': [],

          'preprocessing_backend': 'python',

          'luna_segment': data_dir + '$LUNA16SEGMENTATIONPATH/luna16/seg-lungs-LUNA16/',
          # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path': data_dir + '$LUNA16PROPOCESSPATH/',
          'luna_data': data_dir + '$DOWNLOADLUNA16PATH/',
          'luna_label': data_dir + '$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv'
          }

import os

if __name__ == '__main__':

    # 打开文件
    # path = config['luna_segment']
    path = config['train_data_path'][0]
    dirs = os.listdir(path)

    # 输出所有文件和文件夹
    for file in dirs:
        print(file)
